<?php
/**
 * Created by PhpStorm.
 * User: tom
 * Date: 3/9/21
 * Time: 1:25 PM
 */

namespace Elhelper\modules\stravaApiModule\Controllers;

use Elhelper\common\Singleton;

class StravaApiWebhookHandle extends Singleton {
	public function __init() {
		parent::__init(); // TODO: Change the autogenerated stub
	}


	public function verifyWebhookStrava() {
		$json    = file_get_contents( "php://input" );
		$headers = getallheaders();
		$data    = json_decode( $json, false, 512, JSON_BIGINT_AS_STRING );
		if ( 0 < strlen( $json ) && isset( $headers["X-Zevent-Signature"] ) ) :
			if ( $data ) :
				// Calculate the MAC value from received data
				$mac_1 = "mac=" . hash( "sha256", $data->app_id . $json . $data->timestamp . OA_SECRET_KEY );
				$mac_2 = $headers["X-Zevent-Signature"];

				if ( 0 === strcmp( $mac_1, $mac_2 ) ) :
					return true;
				endif;
			endif;
		endif;

		return false;
	}

	public function verifyAccessTokenStrava() {

		return true;
	}

}