<?php
/**
 * Created by PhpStorm.
 * User: tom
 * Date: 6/30/21
 * Time: 11:09 PM
 */

namespace Elhelper\modules\activityModule\controller;


use Elhelper\common\Singleton;

class ActivityController extends Singleton {

	protected static $_instance;

	public function __init() {
		parent::__init(); // TODO: Change the autogenerated stub

	}


}